package org.ibm.fis.spring_boot_soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.7.0.redhat-611423
 * 2017-03-04T22:27:06.693Z
 * Generated source version: 2.7.0.redhat-611423
 * 
 */
@WebService(targetNamespace = "http://www.examples.com/wsdl/HelloService.wsdl", name = "Hello_PortType")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface HelloPortType {

    @WebMethod(action = "sayHello")
    @WebResult(name = "greeting", targetNamespace = "", partName = "greeting")
    public java.lang.String sayHello(
        @WebParam(partName = "firstName", name = "firstName", targetNamespace = "")
        java.lang.String firstName
    );
}
